# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 319d17006cb493d1151e14f0d4738b641ab8c5aba7cce43fcd4477d4859ca6016a8dc57909c30b641cb61a571ff692a8901775b2dcc6d1d4e38a0f536b34f34f

test:
  secret_key_base: 6b75631919d8fabc9ec38e13c289a1804c3b391cf51b67215b4bd61c73ae168dae290f1680aca24e312c31c09c7dae43c66094a7b625d4430212a8e4286dfc77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
